### ISSUE TITLE
Improve Event Consumption by Exposing Internal Event API Externally

### ISSUE THREAD

**Issue by yanmxa** [project-kessel/inventory-api#243]
I’m trying to consume inventory events from Kafka, but it currently takes a considerable amount of time to unmarshal or decode the event data. To improve this, I suggest exposing the internal event API externally. This would allow consumers to more easily decode the event data without the need for heavy unmarshaling on their side.

The relevant code here: [inventory-api/event.go](https://github.com/project-kessel/inventory-api/blob/main/internal/eventing/api/event.go#L23)

By making this change, we can streamline the event consumption process and improve performance for consumers.

**Comment by akoserwal** [comment]
Thanks for raising the issue, we can review the event to be exposed for clients

**Comment by yanmxa** [comment]
Thanks @akoserwal! I opened a Jira task to trace it. https://issues.redhat.com/browse/RHCLOUD-36298
